Known Py extends,Update error template. update db.
Added new options to parser known extends for python types.
known extends that end with ._ direct parsers to import
from pyton.
uno.Exception now inherites from builtins.Exception
This is done by adding:
    com.sun.star.uno.Exception: ["Exception._"]

Error template now generates fields. No constructor needed.

Database has extends and full_import table id reworked.
The id primary fields were autonumbered. This caused an error
on update where duplicates were being added with new id's.
Now id's are hash strings generated in code.